# Generated by Django 3.0.3 on 2020-09-12 15:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('company_name', models.CharField(blank=True, max_length=180, null=True)),
                ('company_logo', models.CharField(blank=True, max_length=180, null=True)),
                ('created_on', models.DateField()),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(blank=True, max_length=80, null=True)),
                ('module_is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'module',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_name', models.CharField(blank=True, max_length=80, null=True)),
                ('permission_is_active', models.BooleanField(default=False)),
                ('permission_admin', models.BooleanField(default=False)),
                ('permission_user', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='System_create_limit',
            fields=[
                ('system_create_limit_id', models.AutoField(primary_key=True, serialize=False)),
                ('system_create_limit_user', models.IntegerField()),
                ('system_create_limit_admin', models.IntegerField()),
            ],
            options={
                'db_table': 'system_create_limit',
            },
        ),
        migrations.CreateModel(
            name='System_group_all',
            fields=[
                ('system_group_all_id', models.AutoField(primary_key=True, serialize=False)),
                ('system_group_all_name', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'system_group_all',
            },
        ),
        migrations.CreateModel(
            name='System_permission_all',
            fields=[
                ('system_permission_all_id', models.AutoField(primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.Permission')),
                ('system_group_all', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.System_group_all')),
            ],
            options={
                'db_table': 'system_permission_all',
            },
        ),
        migrations.CreateModel(
            name='System_group_limit',
            fields=[
                ('system_group_limit_id', models.AutoField(primary_key=True, serialize=False)),
                ('system_create_limit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.System_create_limit')),
                ('system_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.System_group_all')),
            ],
            options={
                'db_table': 'system_group_limit',
            },
        ),
        migrations.CreateModel(
            name='Purchased_plan',
            fields=[
                ('purchased_plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchased_plan_name', models.CharField(blank=True, max_length=80, null=True)),
                ('purchased_plan_is_active', models.BooleanField(default=False)),
                ('system_group_all', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.System_group_all')),
            ],
            options={
                'db_table': 'purchased_plan',
            },
        ),
        migrations.CreateModel(
            name='Permission_has_module',
            fields=[
                ('permission_has_module_id', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.Module')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.Permission')),
            ],
            options={
                'db_table': 'permission_has_module',
            },
        ),
        migrations.CreateModel(
            name='Company_has_system_permission',
            fields=[
                ('company_has_system_permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.Company')),
                ('system_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.System_group_all')),
            ],
            options={
                'db_table': 'company_has_system_permission',
            },
        ),
    ]
