# Generated by Django 3.0.3 on 2020-09-12 15:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('migrationCore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_has_system_permission',
            old_name='system_group',
            new_name='system_group_all',
        ),
        migrations.RenameField(
            model_name='system_group_limit',
            old_name='system_group',
            new_name='system_group_all',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user_username', models.CharField(max_length=100, unique=True)),
                ('user_password', models.CharField(blank=True, max_length=80, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.Company')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Company_users_limit_count',
            fields=[
                ('company_users_limit_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_users_limit_user', models.IntegerField(default=0)),
                ('company_users_limit_admin', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.Company')),
            ],
            options={
                'db_table': 'company_users_limit_count',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('admin_username', models.CharField(max_length=100, unique=True)),
                ('admin_is_active', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.Company')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
