# Generated by Django 3.0.6 on 2020-09-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrationCore', '0003_admin_admin_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company_has_system_permission',
            new_name='Company_has_system_group_all',
        ),
        migrations.RenameField(
            model_name='company_has_system_group_all',
            old_name='company_has_system_permission_id',
            new_name='company_has_system_group_all_id',
        ),
        migrations.AddField(
            model_name='company',
            name='company_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='company_has_system_group_all',
            table='company_has_system_group_all',
        ),
    ]
