# Generated by Django 3.0.6 on 2020-09-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrationCore', '0004_auto_20200914_1436'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company_users_limit_count',
            new_name='Company_users_current',
        ),
        migrations.RenameField(
            model_name='company_users_current',
            old_name='company_users_limit_admin',
            new_name='company_users_current_admin',
        ),
        migrations.RenameField(
            model_name='company_users_current',
            old_name='company_users_limit_id',
            new_name='company_users_current_id',
        ),
        migrations.RenameField(
            model_name='company_users_current',
            old_name='company_users_limit_user',
            new_name='company_users_current_user',
        ),
        migrations.AlterField(
            model_name='company',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='company_users_current',
            table='company_users_current',
        ),
    ]
