# Generated by Django 3.0.6 on 2020-09-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrationCore', '0005_auto_20200916_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_create_limit',
            name='system_create_limit_storage',
            field=models.IntegerField(default=0),
        ),
    ]
