# Generated by Django 3.0.6 on 2020-09-16 09:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('migrationCore', '0006_system_create_limit_system_create_limit_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_logo',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
    ]
