# Generated by Django 3.0.6 on 2020-09-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migrationCore', '0009_auto_20200916_1700'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company_users_current',
        ),
    ]
