# Generated by Django 3.0.6 on 2020-09-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrationCore', '0010_delete_company_users_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='System_token',
            fields=[
                ('system_token_id', models.AutoField(primary_key=True, serialize=False)),
                ('system_token', models.CharField(max_length=150, unique=True)),
                ('member_public_id', models.CharField(max_length=150)),
                ('created_on', models.DateField()),
            ],
            options={
                'db_table': 'system_token',
            },
        ),
    ]
