# Generated by Django 3.0.6 on 2020-09-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrationCore', '0011_system_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_token',
            name='member_public_id',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='system_token',
            name='system_token',
            field=models.CharField(max_length=220, unique=True),
        ),
    ]
