# Generated by Django 3.0.6 on 2020-09-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrationCore', '0013_auto_20200921_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_token',
            name='created_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='system_token',
            name='system_token',
            field=models.UUIDField(unique=True),
        ),
    ]
