# Generated by Django 3.0.6 on 2020-09-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migrationCore', '0015_auto_20200921_1604'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
