# Generated by Django 3.0.6 on 2020-09-21 11:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('migrationCore', '0016_auto_20200921_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('team_name', models.CharField(max_length=120)),
                ('team_avatar', models.CharField(max_length=180)),
                ('team_is_active', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.Admin')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.Company')),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='Team_has_users',
            fields=[
                ('team_has_users_id', models.AutoField(primary_key=True, serialize=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.User')),
            ],
            options={
                'db_table': 'team_has_users',
            },
        ),
    ]
