# Generated by Django 3.0.6 on 2020-09-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrationCore', '0017_team_team_has_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_avatar',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
