# Generated by Django 3.0.6 on 2020-09-23 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrationCore', '0018_auto_20200921_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('userdetails_id', models.AutoField(primary_key=True, serialize=False)),
                ('userdetails_employee_id', models.CharField(blank=True, max_length=80, null=True)),
                ('userdetails_firstname', models.CharField(blank=True, max_length=80, null=True)),
                ('userdetails_lastname', models.CharField(blank=True, max_length=80, null=True)),
                ('userdetails_phone', models.CharField(blank=True, max_length=80, null=True)),
                ('userdetails_email', models.CharField(blank=True, max_length=80, null=True)),
                ('userdetails_position', models.CharField(blank=True, max_length=80, null=True)),
                ('userdetails_avatar', models.CharField(blank=True, max_length=104, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.User')),
            ],
            options={
                'db_table': 'userdetails',
            },
        ),
    ]
