# Generated by Django 3.0.6 on 2020-09-25 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrationCore', '0020_auto_20200925_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_permission_all',
            name='permission',
        ),
        migrations.AddField(
            model_name='permission',
            name='permission_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='system_permission_all',
            name='permission_has_module',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='migrationCore.Permission_has_module'),
        ),
    ]
