# Generated by Django 3.1.1 on 2020-09-27 14:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('migrationCore', '0021_auto_20200925_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('job_number', models.CharField(blank=True, max_length=80, null=True)),
                ('job_name', models.CharField(blank=True, max_length=80, null=True)),
                ('job_created', models.DateTimeField()),
                ('job_startdate', models.DateField()),
                ('job_enddate', models.DateField()),
                ('job_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.admin')),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('priority_id', models.AutoField(primary_key=True, serialize=False)),
                ('priority_name', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'priority',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('project_number', models.CharField(blank=True, max_length=80, null=True)),
                ('project_name', models.CharField(blank=True, max_length=80, null=True)),
                ('project_desc', models.TextField()),
                ('project_startdate', models.DateTimeField()),
                ('project_enddate', models.DateTimeField()),
                ('project_created', models.DateTimeField()),
                ('project_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.admin')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='migrationCore.status')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='User_has_job',
            fields=[
                ('user_has_job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.job')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='migrationCore.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.user')),
            ],
            options={
                'db_table': 'user_has_job',
            },
        ),
        migrations.CreateModel(
            name='Team_has_job',
            fields=[
                ('team_has_job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.job')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='migrationCore.status')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.team')),
            ],
            options={
                'db_table': 'team_has_job',
            },
        ),
        migrations.CreateModel(
            name='Project_has_team',
            fields=[
                ('project_has_team_id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.project')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.team')),
            ],
            options={
                'db_table': 'project_has_team',
            },
        ),
        migrations.CreateModel(
            name='Project_has_job',
            fields=[
                ('project_has_job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.job')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.project')),
            ],
            options={
                'db_table': 'project_has_job',
            },
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('jobdetails_id', models.AutoField(primary_key=True, serialize=False)),
                ('jobdetails_location', models.TextField(blank=True, null=True)),
                ('jobdetails_desc', models.TextField(blank=True, max_length=80, null=True)),
                ('jobdetails_note', models.TextField(default='')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.job')),
            ],
            options={
                'db_table': 'jobdetails',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='migrationCore.priority'),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='migrationCore.status'),
        ),
    ]
