# Generated by Django 3.1.1 on 2020-09-27 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrationCore', '0022_auto_20200927_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestones',
            fields=[
                ('milestones_id', models.AutoField(primary_key=True, serialize=False)),
                ('milestones_name', models.TextField(blank=True, null=True)),
                ('milestones_enddate', models.DateTimeField()),
                ('milestones_desc', models.TextField()),
                ('milestones_created', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.company')),
                ('milestones_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.admin')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.project')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='migrationCore.status')),
            ],
            options={
                'db_table': 'milestones',
            },
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='jobdetails_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Milestones_has_job',
            fields=[
                ('milestones_has_job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.job')),
                ('milestones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrationCore.milestones')),
            ],
            options={
                'db_table': 'milestones_has_job',
            },
        ),
    ]
